---
# Admins can bypass the message limits
admins:
  -  # Example: '123456789012345678'

# Defines which channels the bot can respond in
channel_whitelist:
  -  # Example: '123456789012345678'
enable_whitelist: false

# Limits the number of requests a user can make in a given time frame
allowed_messages_per_interval: 30
timeout_interval_mins: 10

can_respond_to_dm: true

presence_message_path: "resources/default_presence_message_storage.json"
presence_message_interval_mins: 60
