---
admins:
  -  # Example: '123456789012345678'
channel_whitelist:
  -  # Example: '123456789012345678'
enable_whitelist: false
allowed_messages_per_interval: 30
timeout_interval_mins: 10
stream_output: true
stream_edit_interval_secs: 0.5
